### ISSUE TITLE
Does not work with new reddit userpages

### ISSUE THREAD

**Issue by morpheuskafka** [j0be/PowerDeleteSuite#1]
It just pulls up the "designed to be run from userpage" because `/u/` redirects to `/user/` now

**Comment by Poliwrath** [comment]
https://reddit.com/u/me/overview

**Comment by morpheuskafka** [comment]
@Poliwrath Thanks! I had been searching for a link like that for the past several months!

**Comment by j0be** [comment]
As an aside on this, I also updated the bookmarklet to go there directly, so this should no longer be an issue.
