### ISSUE TITLE
"Overview" page leads to log in/out loop and error page. 

### ISSUE THREAD

**Issue by jtheletter** [j0be/PowerDeleteSuite#11]
I've tried Chrome and Firefox, regular and incognito/private, on macOS. 

Whenever I click the PowerDeleteSuite bookmark, it alerts "This script is designed to be run from your user profile on reddit. Would you like to go there now?". I click OK, and it loads a "cannot be reached" page for a split second, then it appears to log me out (login and join buttons appear in the top right, and it loads https://www.reddit.com/user/~/overview, which looks broken (it has partially styled elements that are devoid of most content. 

![Screen Shot 2019-05-25 at 11 54 47](https://user-images.githubusercontent.com/49571924/58373511-1450e580-7ee4-11e9-8018-14cf15f00761.png)

Network tools show several errors. 

![Screen Shot 2019-05-25 at 11 49 45](https://user-images.githubusercontent.com/49571924/58373512-19159980-7ee4-11e9-90d3-760ccaebd3a2.png)

Visiting https://reddit.com/u/me/overview per https://github.com/j0be/PowerDeleteSuite/issues/1 made no difference. 

I've not had trouble with this Suite on my older account, only on my newer account.

**Comment by ZacharyDavidSaunders** [comment]
This seems to be caused by the Reddit redesign. Try going to `https://old.reddit.com/user/<yourUsernameHere>/overview` and then starting the bookmarklet from there.

**Comment by ZacharyDavidSaunders** [comment]
@j0be Hi, I'm a new contributor, let me know what you think about this.

**Comment by jtheletter** [comment]
Visiting https://old.reddit.com/u/me/overview solved it, thank you.

**Comment by 2fst4u** [comment]
I've been getting this issue for a while now. Has this been pushed to the applet so I can run the script normally now?

**Comment by ZacharyDavidSaunders** [comment]
@2fst4u No, it's still broken. It seems that @j0be hasn't noticed this yet.

**Comment by wadie** [comment]
@2fst4u @ZacharyDavidSaunders this PR https://github.com/j0be/PowerDeleteSuite/pull/13 fixes it

**Comment by ZacharyDavidSaunders** [comment]
@wadie how is this different from my PR? (https://github.com/j0be/PowerDeleteSuite/pull/12)

**Comment by wadie** [comment]
@ZacharyDavidSaunders it's not, I simply didn't notice we had one open.
