### ISSUE TITLE
"Not found" on https://www.reddit.com/user/USERNAME/overview/

### ISSUE THREAD

**Issue by k3anton** [j0be/PowerDeleteSuite#14]
Hi,

Running Google Chrome on Mac OS Catalina.
Followed the tutorial video.
Navigate to my user reddit page, click the bookmark. It asks if I want to navigate to my page, I accept.
I get "Not found". 

I believe /overview/ is depricated in terms of navigation on Reddit? If I remove /overview/ from the URL, it automatically lands on my user overview page.

**Comment by Trevo525** [comment]
I am having this same issue. I hope it can get fixed soon.

**Comment by woebegone615** [comment]
Have any of you figured this out yet? I'm having the same problem.

**Comment by woebegone615** [comment]
Hey guys, J0be answered and this is how you fix it. Just go to: https://old.reddit.com/user/YourUsername/overview/

That fixes it and allows you to use it.

**Comment by j0be** [comment]
I haven't been checking my issue log apparently. I released an update today to both the main script and the bookmark to correct this.
