### ISSUE TITLE
no clue how to install and run it

### ISSUE THREAD

**Issue by Tectract** [j0be/PowerDeleteSuite#17]
"drag to the bookmark bar"

OK, I don't use a bookmark bar, and I don't want to be messing with bookmarked scripts. Can't I run it as a userscript or something?

**Comment by wadie** [comment]
dragging to the bookmark bar makes it easier since it directs you to your Reddit posts page.

Anyway you can go to your posts page on old Reddit (not the redesign) and then paste the content of `powerdeletesuite.js` in the console.

**Comment by seantcanavan** [comment]
For FireFox I clicked the 'Bookmarks' button and clicked 'Show All Bookmarks'. You then 'drag' the install button from the website to the bookmark bar. Very weird and something I've never done before but worked perfectly fine. To run the script I just double clicked the bookmark with the reddit tab active in FireFox.

**Comment by ObiDriftKenobi** [comment]
I made a user script for this tool, you can grab it from the repository and feed it to your browser.

Close?

**Comment by j0be** [comment]
I have a video on how to use it on the subreddit

https://www.reddit.com/r/PowerDeleteSuite/comments/6lopm2/how_to_use_power_delete_suite_video_tutorial
