### ISSUE TITLE
Userscript doesn't add tab for PDS

### ISSUE THREAD

**Issue by metronidazole** [j0be/PowerDeleteSuite#26]
I installed the userscript but it fails to add a PDS tab to the overview page. I can see that the script is loaded in my old reddit userpage though. Running the bookmarklet works fine.

Using violentmonkey in the latest stable firefox build.

**Comment by SilverRoll** [comment]
Does it work if you visit https://old.reddit.com/user/<your username>/overview? It works fine for me, I guess the overview part could be removed.

**Comment by metronidazole** [comment]
Hmm seems to be working now. I thought I checked for overview when I first tested this.

In any case, I've edited the userscript to work without overview.

Thanks

**Comment by SilverRoll** [comment]
@SilverRoll actually, that's correct. The bookmarklet requires you to use the overview page and redirectes you there if you're not in it.
