### ISSUE TITLE
Doesn't appear to find older comments

### ISSUE THREAD

**Issue by mminklet** [j0be/PowerDeleteSuite#29]
I still have heaps of comments that are not being deleted that are from years ago, I found them via the pushshift api. I was under the impression that PDS could delete these olders ones, is that not the case? I know that reddits overview page is a complete mess in that it will never show older comments, but I hoped the reddit api would pick them up. I had tried settings the date range a couple of years back, but it's not picking them up.

EG
https://www.reddit.com/r/sysadmin/comments/4ymrx7/deleted_by_user/

My settings are remove everything, filter by date only

**Comment by j0be** [comment]
It runs multiple filters and sorts, each limited to 1k results. You can hit a there's max of 10k results, but likely closer to 4k is the average I often see.
