### ISSUE TITLE
Encountering error causes subsequent items to be excluded from export

### ISSUE THREAD

**Issue by monyxie** [j0be/PowerDeleteSuite#37]
![pds](https://github.com/j0be/PowerDeleteSuite/assets/703164/134e15fb-e711-4f0b-b977-ca12f8186c46)
Please see the screenshot above. An error was encountered when processing the 778th item. When I clicked "retry", it was able to continue processing but the subsequent items were not exported.

**Comment by j0be** [comment]
Yeah, known defect with how PDS builds the csv file. See the open PR if you're curious.
