### ISSUE TITLE
[NOT AN ISSUE] awesome script

### ISSUE THREAD

**Issue by Naturally-Delicious** [j0be/PowerDeleteSuite#4]
the only comment deletor that works today... i jsut wanted to say, bless you kind stranger.

**Comment by j0be** [comment]
Thanks for the complement!

**Comment by sergiotapia** [comment]
@j0be Seriously, this is just terrific. Great job!

**Comment by rocketicv** [comment]
Hey! To avoid cluttering the open issues, I'll jump in here to say I think it's awesome too! I'm using it right now, in fact. Thanks! I starred the repo.
