### ISSUE TITLE
Please remove upvotes / downvotes / saved entries as well!

### ISSUE THREAD

**Issue by YLSnewb** [j0be/PowerDeleteSuite#40]
Hi.

I'm scrubbing clean my reddit history in an effort to destroy any remaining value left in my account.  I noticed that PoweeDeleteSuite doesn't remove upvotes/downvotes/saved posts.  

Can we please add a feature to remove them before the API access goes away?  Thx.

**Comment by ThatOneCalculator** [comment]
That all should be removed if you delete your account after wiping your posts.

**Comment by j0be** [comment]
No

**Comment by ozgunawesome** [comment]
@YLSnewb  are you the guy who was asking about Xmodem support on Flipper Zero on Reddit?

Your messages are deleted, I can't reach you. Open an issue ticket on any of my projects if you wish to communicate
