### ISSUE TITLE
Ran PDS and it worked initially but all comments are back

### ISSUE THREAD

**Issue by groshreez** [j0be/PowerDeleteSuite#41]
I ran Powerdeletesuite and initially it worked but after a couple days, now all my comments/submissions are back again. Not sure how or why this happened.

**Comment by m0d3rnX** [comment]
Thanks for the heads-up, i will wait before deleting the account

**Comment by j0be** [comment]
Most times I see this, it's stuff that was passed the 1k mark. So as reddit reparses its cache, more comments and submissions appear
