### ISSUE TITLE
Request: delete / edit oldest comments and posts and keep newer comments / posts

### ISSUE THREAD

**Issue by go4ino** [j0be/PowerDeleteSuite#49]
Basically titles. 

Im mostly looking to delete and edit comments from over a year ago, but the only time filters are for **most recent** x months/year

**Comment by seamonkey420** [comment]
> you can click on newer/older to switch them

OMG! i am an idiot and was wondering the same. thanks!!!

**Comment by j0be** [comment]
@braboobssiere is correct. Thanks

**Comment by Sada-Mio** [comment]
Can we have both newer/older at the same time or date range? 

Helps limit excess edit of old comment/post PDS already edited. This sometimes retriggers automod notices. Also with a long history it takes 12hrs to finish processing all nodes. 

Example: edit only older than 30days but newer than 1 year
