### ISSUE TITLE
editText is ignored

### ISSUE THREAD

**Issue by christianlegge** [j0be/PowerDeleteSuite#53]
The pd__comments-edit-text input field is checked on validate, but its content is never used. A randomEditString is generated instead, even if an editText is given.

**Comment by shengslogar** [comment]
Workaround for now is to temporarily update your bookmarklet to point to the last version before this change:

```
- var cachBustUrl = 'https://raw.githubusercontent.com/j0be/PowerDeleteSuite/master/powerdeletesuite.js?'
+ var cachBustUrl = 'https://raw.githubusercontent.com/j0be/PowerDeleteSuite/6f96fa40d9964b6fbc05a1b68c95a52d2666e63b/powerdeletesuite.js?'
```

```
javascript:(function() { window.bookmarkver = '1.4'; var isReddit = document.location.hostname.split('.').slice(-2).join('.') === 'reddit.com'; var isOverview = !! document.location.href.match(/\/overview\b/i); if (isReddit && isOverview) { var cachBustUrl = 'https://raw.githubusercontent.com/j0be/PowerDeleteSuite/6f96fa40d9964b6fbc05a1b68c95a52d2666e63b/powerdeletesuite.js?' + (new Date().getDate()); fetch(cachBustUrl).then(function(response) { return response.text(); }).then(function(data) { var script = document.createElement('script'); script.id = 'pd-script'; script.innerHTML = data; document.getElementsByTagName('head')[0].appendChild(script); }).catch(function() { alert('Error retrieving PowerDeleteSuite from GitHub'); }); } else if (confirm('This script can only be run from your own user profile on Reddit. Would you like to go there now?')) { document.location = 'https://old.reddit.com/u/me/overview'; } else { alert('Please go to your Reddit profile before running this script'); } })();
```

**Comment by Sada-Mio** [comment]
Not sure it has been addressed. 

Just processed my account last night.  "Edit comments / self posts" checked but was replaced with **randomEditString**

**Comment by euuurgh** [comment]
@j0be at what point does one ask if this is just abandonware?
This issue has existed for months, and PR 57 fixes it, but you have not accepted it. At the same time there have been commits, just not any fixing this issues.

I am asking this question as there is no point in having a repo with a broken product. Either archive it and let the community rummage through the remains to create a new project out of the ashes, or have people install and use a broken product, realizing too late that it doesn't work

Thank you very much for your understanding

**Comment by Ottaviocr** [comment]
Is anybody planning a fork?

**Comment by euuurgh** [comment]
I have made a fork for personal use for now, as I need the feature, but don't think I can and want to maintain / improve it.

**Comment by euuurgh** [comment]
Thank you very much
