### ISSUE TITLE
[feature-request] Add an option to undo upvotes

### ISSUE THREAD

**Issue by Neph0** [j0be/PowerDeleteSuite#6]
Hello,

I haven't looked at the code and don't know how feasible it would be, but I would really like if this program also had an option to remove all the upvoted posts as well (at least not the archived ones, I guess).

Although it would be strange if upvote/downvote was part of Reddit's public API?

Thanks.

**Comment by j0be** [comment]
I mean, it's doable, but only for posts / comments that are less than 6 months old. Not really sure why you'd want to do that on your account though

**Comment by Neph0** [comment]
It's mostly about getting the account as "empty" as possible.

**Comment by madaidan** [comment]
What posts you upvote/downvote can tell a lot about you. I think this would be a good feature to include.

**Comment by wadie** [comment]
@madaidan You can't undo your vote for posts which get archived after 6 months.
