### ISSUE TITLE
Arc Browser Usage

### ISSUE THREAD

**Issue by MitchTalmadge** [j0be/PowerDeleteSuite#60]
Just wondering if anyone has figured out how to use this with the Arc Browser. It doesn't seem like I can save a "pinned tab" (Arc's idea of "bookmarks") with Javascript in it.

I'll update if I figure anything out.

**Comment by MitchTalmadge** [comment]
The current best way I've figured out is to:
1. Go to `arc://bookmarks` and create a bookmarklet there.
2. Install the Powerlet chrome extension, which lets you run the bookmarklet from an extension: https://chromewebstore.google.com/detail/powerlet/ofecodkcadbenmiknnidnfepbblapgkn
3. Run the bookmarklet from Powerlet

It's not the best, I wish I didn't have to install an extension, but I guess this works.

**Comment by wadie** [comment]
You could also open the console and paste in the code we have in the README

```
javascript:(function() { window.bookmarkver = '1.4'; var isReddit = document.location.hostname.split('.').slice(-2).join('.') === 'reddit.com'; var isOverview = !! document.location.href.match(/\/overview\b/i); if (isReddit && isOverview) { var cachBustUrl = 'https://raw.githubusercontent.com/mykola2312/PowerDeleteSuite/master/powerdeletesuite.js?' + (new Date().getDate()); fetch(cachBustUrl).then(function(response) { return response.text(); }).then(function(data) { var script = document.createElement('script'); script.id = 'pd-script'; script.innerHTML = data; document.getElementsByTagName('head')[0].appendChild(script); }).catch(function() { alert('Error retrieving PowerDeleteSuite from GitHub'); }); } else if (confirm('This script can only be run from your own user profile on Reddit. Would you like to go there now?')) { document.location = 'https://old.reddit.com/u/me/overview'; } else { alert('Please go to your Reddit profile before running this script'); } })();```
