### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by bit-for-byte** [j0be/PowerDeleteSuite#9]
It appears there's no license for this program. I'd suggest something permissive like MIT or BSD.

**Comment by j0be** [comment]
I think in a vastly earlier version before I refactored it I had it as WTFPL. Seriously, use it however you want.

**Comment by bit-for-byte** [comment]
@j0be Thanks for the info and sorry for the late reply. I'll mark this as solved.

**Comment by TechnologyClassroom** [comment]
If I submit a pull request to this effect, would you consider adding it?
